# At the root : /
version: '2'

services:
  front:
    build: ./docker/front/
    ports:
      - 80:80
    volumes:
      - .:/home/docker:ro
      - ./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default

  engine:
    build: ./docker/engine/
    volumes:
      - .:/home/docker:rw
      - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    working_dir: /home/docker
    networks:
      - default
    dns_search:
      - engine

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: florent
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/dbdump:/docker-entrypoint-initdb.d
    networks:
      - default
    dns_search:
      - db

volumes:
  db: {}

networks:
  default: {}
